In [1]:
import pymysql

def get_connection():
    return pymysql.connect(
        host="localhost",
        user="root",
        password="root",
        database="TMDB"
    )

In [12]:
import pandas as pd

movies = pd.read_csv("c:/xampp/perl/vendor/lib/auto/Devel/vscode/TMDB_data/movies.csv")

movies.head()

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
0,157336,Interstellar,en,2014-11-05,169,165000000.0,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...
1,27205,Inception,en,2010-07-15,148,160000000.0,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es..."
2,24428,The Avengers,en,2012-04-25,143,220000000.0,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...
3,155,The Dark Knight,en,2008-07-16,152,185000000.0,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...
4,19995,Avatar,en,2009-12-16,162,237000000.0,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di..."

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           2509 non-null   int64
 1   title              2509 non-null   object
 2   original_language  2509 non-null   object
 3   release_date       2509 non-null   object
 4   runtime            2509 non-null   int64
 5   budget             2509 non-null   float64
 6   revenue            2509 non-null   float64
 7   popularity         2509 non-null   float64
 8   vote_average       2509 non-null   float64
 9   vote_count         2509 non-null   int64
 10  status             2509 non-null   object
 11  overview           2509 non-null   object
dtypes: float64(4), int64(3), object(5)
memory usage: 235.3+ KB

In [14]:
print("Number of rows:", movies.shape[0])
print("Number of columns:", movies.shape[1])

Number of rows: 2509
Number of columns: 12

In [15]:
print(movies.columns)

Index(['movie_id', 'title', 'original_language', 'release_date', 'runtime',
       'budget', 'revenue', 'popularity', 'vote_average', 'vote_count',
       'status', 'overview'],
      dtype='object')

In [16]:
print(movies.isnull().sum())

movie_id             0
title                0
original_language    0
release_date         0
runtime              0
budget               0
revenue              0
popularity           0
vote_average         0
vote_count           0
status               0
overview             0
dtype: int64

In [17]:
print("Duplicate rows:", movies.duplicated().sum())

Duplicate rows: 6

In [18]:
movies = movies.drop_duplicates()

In [19]:
print("Duplicate rows after cleaning:", movies.duplicated().sum())

Duplicate rows after cleaning: 0

In [20]:
print("Duplicate movie IDs:", movies["movie_id"].duplicated().sum())

Duplicate movie IDs: 0

In [21]:
movies[movies["movie_id"].duplicated(keep=False)]

Empty DataFrame
Columns: [movie_id, title, original_language, release_date, runtime, budget, revenue, popularity, vote_average, vote_count, status, overview]
Index: []

In [22]:
print(movies.dtypes)

movie_id               int64
title                 object
original_language     object
release_date          object
runtime                int64
budget               float64
revenue              float64
popularity           float64
vote_average         float64
vote_count             int64
status                object
overview              object
dtype: object

In [23]:
movies["release_date"] = pd.to_datetime(
    movies["release_date"],
    errors="coerce"
)

In [24]:
print(movies["release_date"].dtype)

datetime64[ns]

In [25]:
print("Missing/Invalid dates:")
print(movies["release_date"].isnull().sum())

Missing/Invalid dates:
0

In [26]:
movies.head()

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
0,157336,Interstellar,en,2014-11-05,169,165000000.0,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...
1,27205,Inception,en,2010-07-15,148,160000000.0,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es..."
2,24428,The Avengers,en,2012-04-25,143,220000000.0,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...
3,155,The Dark Knight,en,2008-07-16,152,185000000.0,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...
4,19995,Avatar,en,2009-12-16,162,237000000.0,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di..."

In [27]:
movies.describe()

,movie_id,release_date,runtime,budget,revenue,popularity,vote_average,vote_count
count,2.503000e+03,2503,2503.000000,2.503000e+03,2.503000e+03,2503.000000,2503.000000,2503.000000
mean,1.849104e+05,2007-08-25 01:57:21.789852416,114.413903,5.862966e+07,2.141801e+08,13.691796,6.943193,6193.834998
min,5.000000e+00,1921-01-21 00:00:00,45.000000,0.000000e+00,0.000000e+00,0.017000,2.945000,475.000000
25%,4.939500e+03,2002-04-28 12:00:00,99.000000,1.445000e+07,4.736877e+07,7.450200,6.437000,3027.000000
50%,3.953800e+04,2010-12-10 00:00:00,111.000000,3.750000e+07,1.279000e+08,10.397100,6.949000,4361.000000
75%,3.309705e+05,2017-02-04 12:00:00,126.000000,8.225000e+07,2.711653e+08,14.866200,7.448500,7276.000000
max,1.368170e+06,2026-06-10 00:00:00,242.000000,6.588000e+08,2.923706e+09,438.475700,8.727000,40566.000000
std,2.572987e+05,NaN,21.418867,6.238084e+07,2.718946e+08,18.109296,0.708935,4959.007777

In [28]:
print("Negative budget:", (movies["budget"] < 0).sum())

Negative budget: 0

In [29]:
print("Negative revenue:", (movies["revenue"] < 0).sum())

Negative revenue: 0

In [30]:
print("Invalid runtime:", (movies["runtime"] <= 0).sum())

Invalid runtime: 0

In [31]:
movies["release_year"] = movies["release_date"].dt.year

In [32]:
movies[["title", "release_date", "release_year"]].head()

             title release_date  release_year
0     Interstellar   2014-11-05          2014
1        Inception   2010-07-15          2010
2     The Avengers   2012-04-25          2012
3  The Dark Knight   2008-07-16          2008
4           Avatar   2009-12-16          2009

In [33]:
movies["profit"] = movies["revenue"] - movies["budget"]

In [34]:
movies[["title", "budget", "revenue", "profit"]].head()

             title       budget       revenue        profit
0     Interstellar  165000000.0  7.466067e+08  5.816067e+08
1        Inception  160000000.0  8.390306e+08  6.790306e+08
2     The Avengers  220000000.0  1.518816e+09  1.298816e+09
3  The Dark Knight  185000000.0  1.004558e+09  8.195584e+08
4           Avatar  237000000.0  2.923706e+09  2.686706e+09

In [35]:
movies["roi"] = np.where(
    movies["budget"] > 0,
    (movies["profit"] / movies["budget"]) * 100,
    np.nan
)

In [36]:
movies[["title", "budget", "revenue", "profit", "roi"]].head()

             title       budget       revenue        profit          roi
0     Interstellar  165000000.0  7.466067e+08  5.816067e+08   352.488913
1        Inception  160000000.0  8.390306e+08  6.790306e+08   424.394144
2     The Avengers  220000000.0  1.518816e+09  1.298816e+09   590.370689
3  The Dark Knight  185000000.0  1.004558e+09  8.195584e+08   443.004564
4           Avatar  237000000.0  2.923706e+09  2.686706e+09  1133.631235

In [37]:
print("Final Shape:", movies.shape)

print("\nMissing Values:")
print(movies.isnull().sum())

print("\nDuplicate Rows:")
print(movies.duplicated().sum())

print("\nData Types:")
print(movies.dtypes)

Final Shape: (2503, 15)

Missing Values:
movie_id              0
title                 0
original_language     0
release_date          0
runtime               0
budget                0
revenue               0
popularity            0
vote_average          0
vote_count            0
status                0
overview              0
release_year          0
profit                0
roi                  90
dtype: int64

Duplicate Rows:
0

Data Types:
movie_id                      int64
title                        object
original_language            object
release_date         datetime64[ns]
runtime                       int64
budget                      float64
revenue                     float64
popularity                  float64
vote_average                float64
vote_count                    int64
status                       object
overview                     object
release_year                  int32
profit                      float64
roi                         float64
dtype: object

In [38]:
movies.to_csv("cleaned_movies.csv", index=False)

print("Cleaned movies dataset saved successfully!")

Cleaned movies dataset saved successfully!

In [39]:
print(movies.columns)

Index(['movie_id', 'title', 'original_language', 'release_date', 'runtime',
       'budget', 'revenue', 'popularity', 'vote_average', 'vote_count',
       'status', 'overview', 'release_year', 'profit', 'roi'],
      dtype='object')

In [41]:
movies["release_date"].head(100)

0    2014-11-05
1    2010-07-15
2    2012-04-25
3    2008-07-16
4    2009-12-16
        ...
95   2017-01-19
96   2016-02-11
97   2009-06-02
98   2016-12-01
99   2014-09-10
Name: release_date, Length: 100, dtype: datetime64[ns]

In [42]:
print(movies[["release_date"]].head(10))
print(movies["release_date"].dtype)

  release_date
0   2014-11-05
1   2010-07-15
2   2012-04-25
3   2008-07-16
4   2009-12-16
5   2016-02-09
6   1999-10-15
7   2018-04-25
8   1994-09-23
9   1994-09-10
datetime64[ns]

In [43]:
genres = pd.read_csv(
    r"c:\xampp\perl\vendor\lib\auto\Devel\vscode\TMDB_data\genres.csv"
)

genres.head()

   genre_id genre_name
0        28     Action
1        12  Adventure
2        16  Animation
3        35     Comedy
4        80      Crime

In [44]:
genres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   genre_id    19 non-null     int64
 1   genre_name  19 non-null     object
dtypes: int64(1), object(1)
memory usage: 432.0+ bytes

In [45]:
print("Rows:", genres.shape[0])
print("Columns:", genres.shape[1])

Rows: 19
Columns: 2

In [46]:
print(genres.columns)

Index(['genre_id', 'genre_name'], dtype='object')

In [47]:
print(genres.isnull().sum())

genre_id      0
genre_name    0
dtype: int64

In [48]:
print("Duplicate rows:", genres.duplicated().sum())

Duplicate rows: 0

In [49]:
print(genres.columns)

Index(['genre_id', 'genre_name'], dtype='object')

In [50]:
print("Duplicate genre IDs:", genres["genre_id"].duplicated().sum())

Duplicate genre IDs: 0

In [51]:
genres[genres["genre_id"].duplicated(keep=False)]

Empty DataFrame
Columns: [genre_id, genre_name]
Index: []

In [52]:
genres = genres.drop_duplicates()

In [53]:
genres["genre_name"].value_counts()

genre_name
Action             1
Adventure          1
Animation          1
Comedy             1
Crime              1
Documentary        1
Drama              1
Family             1
Fantasy            1
History            1
Horror             1
Music              1
Mystery            1
Romance            1
Science Fiction    1
TV Movie           1
Thriller           1
War                1
Western            1
Name: count, dtype: int64

In [54]:
print("Empty genre names:")

print(
    (genres["genre_name"].isnull() |
     (genres["genre_name"].str.strip() == "")).sum()
)

Empty genre names:
0

In [55]:
genres["genre_name"] = genres["genre_name"].str.strip()

In [56]:
print(genres.dtypes)

genre_id       int64
genre_name    object
dtype: object

In [57]:
print("Final Shape:", genres.shape)

print("\nMissing Values:")
print(genres.isnull().sum())

print("\nDuplicate Rows:")
print(genres.duplicated().sum())

print("\nDuplicate Genre IDs:")
print(genres["genre_id"].duplicated().sum())

Final Shape: (19, 2)

Missing Values:
genre_id      0
genre_name    0
dtype: int64

Duplicate Rows:
0

Duplicate Genre IDs:
0

In [60]:
genres.to_csv(
    r"c:\xampp\perl\vendor\lib\auto\Devel\vscode\TMDB_data\cleaned_genres.csv",
    index=False
)

print("Cleaned genres dataset saved successfully!")

Cleaned genres dataset saved successfully!

In [61]:
movie_genres = pd.read_csv(
    r"c:\xampp\perl\vendor\lib\auto\Devel\vscode\TMDB_data\movie_genres.csv"
)

movie_genres.head()

   movie_id  genre_id
0    157336        12
1    157336        18
2    157336       878
3     27205        28
4     27205       878

In [62]:
movie_genres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6888 entries, 0 to 6887
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  6888 non-null   int64
 1   genre_id  6888 non-null   int64
dtypes: int64(2)
memory usage: 107.8 KB

In [63]:
print("Rows:", movie_genres.shape[0])
print("Columns:", movie_genres.shape[1])

Rows: 6888
Columns: 2

In [64]:
print(movie_genres.isnull().sum())

movie_id    0
genre_id    0
dtype: int64

In [65]:
print("Duplicate rows:", movie_genres.duplicated().sum())

Duplicate rows: 10

In [66]:
movie_genres = movie_genres.drop_duplicates()

In [67]:
print("Duplicate rows after cleaning:", movie_genres.duplicated().sum())

Duplicate rows after cleaning: 0

In [81]:
print(movie_genres.columns)

Index(['movie_id', 'genre_id'], dtype='object')

In [ ]:
movie_keywords.duplicated().sum()

np.int64(20)

In [69]:
duplicates = movie_genres.duplicated(
    subset=["movie_id", "genre_id"]
).sum()

print("Duplicate movie-genre relationships:", duplicates)

Duplicate movie-genre relationships: 0

In [70]:
print("Final Shape:", movie_genres.shape)

print("\nMissing Values:")
print(movie_genres.isnull().sum())

print("\nDuplicate Rows:")
print(movie_genres.duplicated().sum())

Final Shape: (6878, 2)

Missing Values:
movie_id    0
genre_id    0
dtype: int64

Duplicate Rows:
0

In [71]:
movie_genres.to_csv(
    r"c:\xampp\perl\vendor\lib\auto\Devel\vscode\TMDB_data\cleaned_movie_genres.csv",
    index=False
)

print("Cleaned movie_genres dataset saved successfully!")

Cleaned movie_genres dataset saved successfully!

In [28]:
movie_keywords = pd.read_csv(
    r"c:\xampp\perl\vendor\lib\auto\Devel\vscode\TMDB_data\movie_keywords.csv"
)

movie_keywords.head()

   movie_id  keyword_id                    keyword_name
0    157336        1612                      spacecraft
1    157336        4776               race against time
2    157336         310  artificial intelligence (a.i.)
3    157336        1432                            nasa
4    157336        1521                       time warp

In [29]:
movie_keywords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41701 entries, 0 to 41700
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      41701 non-null  int64
 1   keyword_id    41701 non-null  int64
 2   keyword_name  41701 non-null  object
dtypes: int64(2), object(1)
memory usage: 977.5+ KB

In [30]:
print("Rows and Columns:", movie_keywords.shape)

Rows and Columns: (41701, 3)

In [31]:
movie_keywords.isnull().sum()

movie_id        0
keyword_id      0
keyword_name    0
dtype: int64

In [32]:
movie_keywords.duplicated().sum()

np.int64(20)

In [33]:
movie_keywords = movie_keywords.drop_duplicates()

In [34]:
movie_keywords.duplicated().sum()

np.int64(0)

In [35]:
movie_keywords["movie_id"].duplicated().sum()

np.int64(39185)

In [36]:
print(movie_keywords.columns)

Index(['movie_id', 'keyword_id', 'keyword_name'], dtype='object')

In [37]:
movie_keywords[movie_keywords["movie_id"].duplicated(keep=False)]

       movie_id  keyword_id                    keyword_name
0        157336        1612                      spacecraft
1        157336        4776               race against time
2        157336         310  artificial intelligence (a.i.)
3        157336        1432                            nasa
4        157336        1521                       time warp
...         ...         ...                             ...
41676     19901       34079                           death
41677     19901      160153                            dead
41678     19901      232469                    urban gothic
41679     19901      243150                   brutal deaths
41680     19901      325824                         hopeful

[41677 rows x 3 columns]

In [38]:
movie_keywords.describe()

           movie_id     keyword_id
count  4.168100e+04   41681.000000
mean   1.702690e+05  105365.444711
std    2.567127e+05  121033.924775
min    5.000000e+00      30.000000
25%    1.894000e+03    4379.000000
50%    1.824000e+04   14546.000000
75%    2.977610e+05  207883.000000
max    1.368166e+06  380091.000000

In [39]:
movie_keywords.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41681 entries, 0 to 41680
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      41681 non-null  int64
 1   keyword_id    41681 non-null  int64
 2   keyword_name  41681 non-null  object
dtypes: int64(2), object(1)
memory usage: 1.3+ MB

In [40]:
movie_keywords['keyword_id'].unique()

array([  1612,   4776,    310, ..., 229481, 340609, 243150])

In [41]:
movie_keywords['movie_id'].unique()

array([157336,  27205,  24428, ...,  13680,   7461,  19901])

 print("\nDuplicate Rows:")
    print(movie_keywords.duplicated().sum())

In [42]:
print("\nDuplicate Rows:")
print(movie_keywords.duplicated().sum())

Duplicate Rows:
0

In [43]:
movie_keywords.drop_duplicates(inplace=True)

In [44]:
duplicates = movie_keywords.duplicated(
    subset=["movie_id", "keyword_id", "keyword_name"]
).sum()

print("Duplicate keyword relationships:", duplicates)

Duplicate keyword relationships: 0

In [45]:
print("Final Shape:", movie_keywords.shape)

print("\nMissing Values:")
print(movie_keywords.isnull().sum())

print("\nDuplicate Rows:")
print(movie_keywords.duplicated().sum())

Final Shape: (41681, 3)

Missing Values:
movie_id        0
keyword_id      0
keyword_name    0
dtype: int64

Duplicate Rows:
0

In [46]:
movie_keywords.to_csv(
    r"c:\xampp\perl\vendor\lib\auto\Devel\vscode\TMDB_data\cleaned_movie_keywords.csv",
    index=False
)

print("Cleaned movie_keywords dataset saved successfully!")

Cleaned movie_keywords dataset saved successfully!

In [1]:
import pandas as pd

cast = pd.read_csv(
    r"c:\xampp\perl\vendor\lib\auto\Devel\vscode\TMDB_data\cast.csv"
)

cast.head()

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
0,1,157336,10297,Matthew McConaughey,Cooper,0
1,2,157336,1813,Anne Hathaway,Brand,1
2,3,157336,3895,Michael Caine,Professor Brand,2
3,4,157336,83002,Jessica Chastain,Murph,3
4,5,157336,1893,Casey Affleck,Tom,4

In [2]:
cast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24917 entries, 0 to 24916
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cast_row_id     24917 non-null  int64
 1   movie_id        24917 non-null  int64
 2   person_id       24917 non-null  int64
 3   actor_name      24917 non-null  object
 4   character_name  24906 non-null  object
 5   cast_order      24917 non-null  int64
dtypes: int64(4), object(2)
memory usage: 1.1+ MB

In [3]:
print(cast.columns)

Index(['cast_row_id', 'movie_id', 'person_id', 'actor_name', 'character_name',
       'cast_order'],
      dtype='object')

In [4]:
print(cast.isnull().sum())

cast_row_id        0
movie_id           0
person_id          0
actor_name         0
character_name    11
cast_order         0
dtype: int64

In [5]:
cast = cast.drop_duplicates()

In [6]:
print(cast.isnull().sum())

cast_row_id        0
movie_id           0
person_id          0
actor_name         0
character_name    11
cast_order         0
dtype: int64

In [7]:
print("Duplicate rows after cleaning:", cast.duplicated().sum())

Duplicate rows after cleaning: 0

In [8]:
print("Missing character names:")
print(cast["character_name"].isnull().sum())

Missing character names:
11

In [9]:
cast["character_name"] = cast["character_name"].fillna("Unknown")

In [10]:
cast["actor_name"] = cast["actor_name"].str.strip()
cast["character_name"] = cast["character_name"].str.strip()

In [12]:
print(cast.columns.tolist())

['cast_row_id', 'movie_id', 'person_id', 'actor_name', 'character_name', 'cast_order']

In [13]:
cast.head()

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
0,1,157336,10297,Matthew McConaughey,Cooper,0
1,2,157336,1813,Anne Hathaway,Brand,1
2,3,157336,3895,Michael Caine,Professor Brand,2
3,4,157336,83002,Jessica Chastain,Murph,3
4,5,157336,1893,Casey Affleck,Tom,4

In [ ]:
duplicates = cast.duplicated(
    subset=["movie_id", "actor_name", "character_name"]
).sum()

print("Duplicate cast relationships:", duplicates)

Duplicate cast relationships: 0

In [16]:
cast = cast.drop_duplicates(
    subset=["movie_id", "actor_name", "character_name"]
)

In [17]:
print("Final Shape:", cast.shape)

print("\nMissing Values:")
print(cast.isnull().sum())

print("\nDuplicate Rows:")
print(cast.duplicated().sum())

print("\nData Types:")
print(cast.dtypes)

Final Shape: (24902, 6)

Missing Values:
cast_row_id       0
movie_id          0
person_id         0
actor_name        0
character_name    0
cast_order        0
dtype: int64

Duplicate Rows:
0

Data Types:
cast_row_id        int64
movie_id           int64
person_id          int64
actor_name        object
character_name    object
cast_order         int64
dtype: object

In [18]:
cast.to_csv(
    r"c:\xampp\perl\vendor\lib\auto\Devel\vscode\TMDB_data\cleaned_cast.csv",
    index=False
)

print("Cleaned cast dataset saved successfully!")

Cleaned cast dataset saved successfully!

In [47]:
crew = pd.read_csv(
    r"c:\xampp\perl\vendor\lib\auto\Devel\vscode\TMDB_data\crew.csv"
)

crew.head()

   crew_row_id  movie_id  person_id        person_name       job department
0            1    157336        527     Jonathan Nolan    Writer    Writing
1            2    157336        525  Christopher Nolan    Writer    Writing
2            3    157336        525  Christopher Nolan  Director  Directing
3            4     27205        525  Christopher Nolan    Writer    Writing
4            5     27205        525  Christopher Nolan  Director  Directing

In [48]:
print(crew.columns.tolist())

['crew_row_id', 'movie_id', 'person_id', 'person_name', 'job', 'department']

In [49]:
crew.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7297 entries, 0 to 7296
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   crew_row_id  7297 non-null   int64
 1   movie_id     7297 non-null   int64
 2   person_id    7297 non-null   int64
 3   person_name  7297 non-null   object
 4   job          7297 non-null   object
 5   department   7297 non-null   object
dtypes: int64(3), object(3)
memory usage: 342.2+ KB

In [50]:
print("Duplicate rows:", crew.duplicated().sum())

Duplicate rows: 8

In [51]:
crew = crew.drop_duplicates()

print("Duplicate rows after cleaning:", crew.duplicated().sum())

Duplicate rows after cleaning: 0

In [54]:
text_columns = crew.select_dtypes(include="object").columns

for column in text_columns:
    crew[column] = crew[column].str.strip()

print("Text columns cleaned successfully!")

Text columns cleaned successfully!

In [55]:
crew.head()

   crew_row_id  movie_id  person_id        person_name       job department
0            1    157336        527     Jonathan Nolan    Writer    Writing
1            2    157336        525  Christopher Nolan    Writer    Writing
2            3    157336        525  Christopher Nolan  Director  Directing
3            4     27205        525  Christopher Nolan    Writer    Writing
4            5     27205        525  Christopher Nolan  Director  Directing

In [56]:
print("Missing values:")
print(crew.isnull().sum())

print("\nDuplicate rows:")
print(crew.duplicated().sum())

Missing values:
crew_row_id    0
movie_id       0
person_id      0
person_name    0
job            0
department     0
dtype: int64

Duplicate rows:
0

In [57]:
print(crew.columns.tolist())

['crew_row_id', 'movie_id', 'person_id', 'person_name', 'job', 'department']

In [59]:
duplicates = crew.duplicated(
    subset=["movie_id", "crew_row_id", "job"]
).sum()

print("Duplicate crew relationships:", duplicates)

Duplicate crew relationships: 0

In [60]:
print("Final Shape:", crew.shape)

print("\nMissing Values:")
print(crew.isnull().sum())

print("\nDuplicate Rows:")
print(crew.duplicated().sum())

print("\nData Types:")
print(crew.dtypes)

Final Shape: (7289, 6)

Missing Values:
crew_row_id    0
movie_id       0
person_id      0
person_name    0
job            0
department     0
dtype: int64

Duplicate Rows:
0

Data Types:
crew_row_id     int64
movie_id        int64
person_id       int64
person_name    object
job            object
department     object
dtype: object

In [61]:
crew.to_csv(
    r"c:\xampp\perl\vendor\lib\auto\Devel\vscode\TMDB_data\cleaned_crew.csv",
    index=False
)

print("Cleaned crew dataset saved successfully!")

Cleaned crew dataset saved successfully!

In [62]:
print(cast.columns.tolist())
print(crew.columns.tolist())

['cast_row_id', 'movie_id', 'person_id', 'actor_name', 'character_name', 'cast_order']
['crew_row_id', 'movie_id', 'person_id', 'person_name', 'job', 'department']